# Generated by Django 5.0.6 on 2024-07-02 01:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.AutoField(
                        db_comment="Auto created ID",
                        primary_key=True,
                        serialize=False,
                        verbose_name="Auto created ID",
                    ),
                ),
                (
                    "password",
                    models.CharField(
                        db_comment="User Password",
                        max_length=128,
                        verbose_name="Password",
                    ),
                ),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True,
                        db_comment="Last login time",
                        null=True,
                        verbose_name="Last login time",
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        db_comment="Administrator status(0:General User, 1:Administrator User)",
                        default=False,
                        verbose_name="Administrator status(0:General User, 1:Administrator User)",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        db_comment="ID to use when login for the user",
                        max_length=16,
                        unique=True,
                        verbose_name="ID to use when login",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_comment="The user's real name",
                        max_length=30,
                        verbose_name="The user's real name",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        db_comment="The user's email address",
                        max_length=254,
                        unique=True,
                        verbose_name="Email Address",
                    ),
                ),
                (
                    "active_status",
                    models.IntegerField(
                        choices=[
                            (0, "Inactive"),
                            (1, "Active"),
                            (2, "On Leave"),
                            (3, "Retired"),
                            (4, "Rejection"),
                        ],
                        db_comment="In-service status(0:inactive, 1:active, 2:on leave, 3:retired, 4:rejection)",
                        default=0,
                        verbose_name="In-service status(0:inactive, 1:active, 2:on leave, 3:retired, 4:rejection)",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_comment="The date the user joined",
                        verbose_name="Joined Date",
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "User",
                "verbose_name_plural": "Users",
                "db_table": "user",
            },
        ),
        migrations.CreateModel(
            name="UserSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("session_key", models.CharField(max_length=40)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User Session",
                "verbose_name_plural": "Users Session",
                "db_table": "user_session",
            },
        ),
    ]
