# Generated by Django 5.0.6 on 2024-07-01 05:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_usersession"),
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="usersession",
            options={
                "verbose_name": "User Session",
                "verbose_name_plural": "Users Session",
            },
        ),
        migrations.RemoveField(
            model_name="user",
            name="is_active",
        ),
        migrations.AddField(
            model_name="user",
            name="active_status",
            field=models.IntegerField(
                choices=[
                    (0, "Inactive"),
                    (1, "Active"),
                    (2, "On Leave"),
                    (3, "Retired"),
                ],
                db_comment="In-service status(0:inactive, 1:active, 2:on leave, 3:retired)",
                default=0,
                verbose_name="In-service status(0:inactive, 1:active, 2:on leave, 3:retired)",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="groups",
            field=models.ManyToManyField(
                blank=True,
                help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                related_name="user_set",
                related_query_name="user",
                to="auth.group",
                verbose_name="groups",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="user_permissions",
            field=models.ManyToManyField(
                blank=True,
                help_text="Specific permissions for this user.",
                related_name="user_set",
                related_query_name="user",
                to="auth.permission",
                verbose_name="user permissions",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="is_superuser",
            field=models.BooleanField(
                db_comment="Administrator status(0:General User, 1:Administrator User)",
                default=False,
                verbose_name="Administrator status(0:General User, 1:Administrator User)",
            ),
        ),
        migrations.AlterModelTable(
            name="usersession",
            table="user_session",
        ),
    ]
