# Generated by Django 5.0.6 on 2024-07-01 05:21

import django.core.serializers.json
import json.decoder
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("counseling", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="counselmanual",
            name="vector",
            field=models.JSONField(
                db_comment="Counsel Manual Vector body for Counselor",
                decoder=json.decoder.JSONDecoder,
                encoder=django.core.serializers.json.DjangoJSONEncoder,
                null=True,
                verbose_name="Counsel Manual Vector body for Counselor",
            ),
        ),
    ]
